version: '3'
services:
  app:
    container_name: mcpfp-api
    build: .
    ports:
      - "9002:9002"  
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/app/api
    command: ["bun", "run", "src/index.ts"]  # Use Bun's watch mode for auto-reloading